#
###################################
# Site wide configuration
####################################
#
title:       "Neverland"
description: "Jay's Technical Zone"
url:  # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "ZHENG ZHOU"
  avatar: avatar.jpg
  job: "Student (Master of Science)"
  bio: "Actively seeking for jobs... ( ¯ □ ¯ ) "
  email: "encorechow1992@gmail.com"
  disqus-shortname:
  twitter:
  facebook: "axieandyangyang"
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: "encorechow"
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: "zhou-zheng-378041a5" #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
